### ISSUE TITLE
Viability of the role of Content Leader

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/AnotherPlanetData#5]
@jasonrohrer 

This role is a near part-time job. The time it takes to plan, organise and test changes is immense, while having to worry about possibly being voted out next week.

Assuming a content leader spends a conservative 10 hours a week doing just this and also assuming they make minimal content additions themselves outside of testing, they'll be left completely empty-handed when it comes to profit sharing.

I consider this a critical problem to the model of this game. No content lead. No AHAP.

I also question the viability of the process to add content. Relying solely on importing content mods (made for client side and does not include transitions!) completely negates the point of Git and GitHub.

GitHub should be treated as the *Hub* of this community, and there should be a viable way to easily submit Pull Requests and make use of the full feature set.

**How can this role, which will likely be shared by a group of people all testing and planning, be more equitable and desirable to fulfil?**

**Comment by DopiePanda** [comment]
I don't have the solution to your question, but I have some comments on how the first week as content leader has been.

It's definitely a big work load, with both setting up the Discord to have somewhere to accept and discuss mods and the editor, etc., and as well that several of the submitted mods have required extra work, on top of creating the transitions (that the some of the mod creators already have done in their own editors). More video resources on how the editor works and it's different sub-systems work would be great to minimize the spread of the quality of submitted mods, cause there is alot of wellwritten documentation on it, but it's spread over many sites, links and documents.

I think more of the time as content lead on my part has been happening outside of the editor, talking to the different users, recieving the submissions, writing feedback, and helping them debug the editor, etc. So I would definitely not mind the transitions being included in the compressed file to further minimize the work required with the mods before comitting them to the repo.

So to me the monetary compensation isn't as important as the success of the game. But future leaders might have other thoughts on this which is completely understandable.

**Comment by connorhsm** [comment]
Appreciate the insight.

I understand and agree regarding the compensation. I'm also not here for a payout, it's been 6 years already. But I'd like to see some clarification as at this time it appears Jason believes this is equitable.

Highlighting the amount of work involved outside the editor is a key point; while expecting the Content Lead to also handle all transitions as a way to get paid for their work feels inadequate.

In the meantime, I believe it may be possible to work out a workflow where transitions could be submitted via a PR, to unify this with content mods, you could also ask OXZ files to also be shared this way, although this may limit some people due to lack of familiarity with Git and GitHub.

Would be happy to work this out over Discord if you'd like.

**Comment by connorhsm** [comment]
In addition, creativity of our limits with Data is likely to be the greatest strength of AHAP. This is stunted by leaving transitions to one person.

**Comment by jasonrohrer** [comment]
Yes, Content Leaders will have their contributions measured in terms of how many transitions they create, when integrating stuff.

I'm not sure what the break-down will be, but if we really see the Content Leaders as point-people and show-runners, they could receive a very high percentage... maybe even 50%

Obviously, they'd be splitting the 50% based on their individual tenures and how much work each one did, in terms of transitions created to integrate stuff.

But yeah, if AHAP ends up being a financial success, I expect that the Content Leaders will be paid handsomely.



And Connor, no, raw git won't work for this, because the content is STRUCTURED and ORDERED.  Each object has a unique numerical ID, and these IDs are created in order when editing.

It works this way to keep the protocol as slim as possible.... the server can tell you about an object with 3 or 4 ascii digits, instead of a 20-digit unique hash ID or something.  Objects can also be stored in the map DB with just 4 bytes (they are 32-bit integers).  For a game with an 1.6x10^19 tile map, full of player-generated stuff, storage space matters, and protocol space---to tell 100+ players about what's on the map---matters too.


But this also means that if people are working in parallel, they will be making collisions in the ID space constantly.

Suppose the most recent object is 108 for both of us.

Now we both make a bunch of new objects in parallel.  I make objects 109, 110, 111, 112.

Meanwhile, you make 109, 110, 111, 112, 113, 114.

We also make all kinds of transitions and animations using these IDs.

Now we commit all this... what happens?

Merging with git is impossible, because your file 109 is different from my file 109, and there's no way to fix it.  And the transitions are a huge mess too.

Essentially, the only way to merge is to throw one person's work away.  Or use some kind of non-git tool to do an OHOL-specific merge.  Which is EXACTLY what the Export and Import functionality of the Editor does.

Git wasn't designed to handle this.  It was made for folders full of source code files.  Not structured, ordered data files.

**Comment by Arcurus** [comment]
1. What to export? --> Just the transitions to the objects that are exportet 
2. What is in case of conflict? --> Display the conflict and ask if import should go on without the listed conflicts. 
3. Provide an option to not export / import transitions

**Comment by jasonrohrer** [comment]
And how do you pick transitions to export?

It's just too error-prone.

Objects (and the animations sounds and sprites that are needed for them) are very atomic and self-contained.  You can pick a bunch of objects, and export those.

But transitions are a tangled web of dependencies.

**Comment by jasonrohrer** [comment]
And my comments about the nature of object IDs were in relation to why we can't just used "git push" for all of this instead of Exporting from the Editor.

YES, the Import/Export feature does all kinds of stuff to handle ID collisions gracefully.  But that code is already very very complicated (to get that right, and not be buggy). 6000 lines of code.

**Comment by Arcurus** [comment]
yea, they are a web, but thats not a big problem. Which one to export? The one directly connected to the exported object see above 1). In case some other object is missing or a double transition, see above 2) than the content leader could ask for the missing objects or resolve the errors himself or just decide to not import the transitions with the errors.

But yea, maybe a better approach would be to provide unique ids (just of for edit reasons not in game) and allow to use merge. I was talking these days with moon a lot how they handle in 2HOL multiple people contributing.
 
They kind of make a workaround and give each contributors their own range of unique Ids. Like the first one has the next 100 the second the next 100 and so on. And then on merge they run a script that provides the final Ids.

If instead the editor would by default use unique ids to operate this process could be made lot easier and a merge could happen without considering the order of Ids, since a script can provide the Ids for a given data repository.

This would simplify the merging process a lot and you wont need mess around with complicating the export function.

**Comment by Arcurus** [comment]
>And my comments about the nature of object IDs were in relation to why we can't just used "git push" for all of this instead of Exporting from the Editor.<

If the editor uses unique ids would it not be possible to just "git push"? In case of merge conflicts git is designed to help solve them. So only thing the editor would need to do is assign unique ids which are then used also for the transitions. A script assigns then the real ids for a given repository bevor server start.
