### ISSUE TITLE
Transitions are missing in export files. Adding them manually is tons of work and easy to mess up for the content leader 

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/AnotherPlanetData#6]
Guess best way to go is to change the editors export function to include the transitions and then give the option on import to also import transitions. 

This path would most likely be the cleanest. I guess it would be good to use unique IDs for objects in the export files or even better use unique ids for all objects and then on import map them to the in game used relative IDs in a given Data Repository. 
So first implement unique IDs for all objects then change the import script to map the unique ids to the in game ids for a given repository.

Ideally on import a list would be shown which objects would be imported and list the conflicts.
This list could allow also to switch off the import of some transitions or objects.

**Comment by Arcurus** [comment]
To be clear: Unique ids would only be used for editing not in the game. So neither server or client knows about them. just the editor knows and need to be changed.

Ok, if the unique ids are stored in the current data files, client or server would need to ignore them on load. An other solution would be to completely separate the objects / transitions files for editing from the ones used in game. This solution would allow to store more data in them that is only needed for editing. 

Or alternatively in the end of a given data file could be an area like the comment section that is just ignored by client and server.  Maybe even the current comment section could be used to store meta editing information..

**Comment by Arcurus** [comment]
Actually for editing purposes normal IDs are completly irrelevant. Unique IDs would be fully enough. Just once the game starts normal IDs are needed and could be automatically generated. This would allow additionally to use normal github source control for merging in new objects and transitions.

**Comment by jasonrohrer** [comment]
Yeah, I decided up-front to not support transitions in the Export files, since it's just so error-prone.

Let's say you're editing... a banana seed.  Bananas are already in the game, along with all the banana farming stuff.

So now you are trying to export your banana seed, and obviously, that means the transitions for creating the seed should be created.  But those depend on Knife and also Banana.  Should those objects be exported too?  But what about Steel and Banana Tree, which are needed to get Knife and Banana?

When exporting something, if we're going to export transitions too, there's no way for the editor to know which prerequisite objects and transitions are needed.  Like... which are new?  Which already exist in the Content Leader's stuff?

And for some more complex objects, like the Rocket, including all prerequisites would mean including like 25% of the tech tree.

But even worse, even if we COULD figure out just what to export, when the Content Leader goes to import this stuff.... what's going to happen if there's a conflict?  Like if something has already changed about Banana Tree in the Leader's tech tree.  What if Knife + Banana already make something else?

So, by exporting transitions---and by extension, prerequisite objects---we're just asking for trouble when we got to merge the content into the Content Leader's stuff.


The truth is that making transitions can really only be the job of one person, or people taking turns.  Someone has to make sure that the transitions fit together and make sense.  Someone has to really think it through.  Someone has to test it all, etc.

So this is going to be up to the Content Leader mostly, or maybe, if you really want to... people taking turns working on the git repo, using carefully pre-approved pull requests.


Sprites, objects, animations, and sounds, on the other hand, can be created in parallel without any worries.  We can just bring them all in as new objects, and easily identify re-used sprites and sounds to avoid duplicating bulk data.


And really, the sprites/objects/animations/sounds are the truly time-consuming part.

Making transitions to hook them all together is really quick, by comparison.
